### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by guyou**
It seems that JSatTrak was initially developped under Windows and code was stored with CRLF convention. Such convention induce difficulties when hacking on an Unix system.

Best practices require that files are stored in Git following LF convention and converted to the host system's convention in working directory.
https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html

This change can produce a lot of conflicts when merging with branches not following the same line ending convention. In this case, you should use 'git merge -Xignore-space-change ...'.

### CODE REVIEW

**Comment by sgano** [comment]
I think I messed something up with my last push/commit, which prevents me from merging this request.  Sorry a bit of a git noob - as I am not sure how to fix this.  But I am on-board with fixing the end of line characters (it was developed initially mostly on Windows)

**Comment by guyou** [comment]
Concerning what you made, I think you initiated the commit "updates for java 7" (SHA1:565a8e2b3bf8280fa6e617aa5d3c6248e556b1c0) directly on top of last version (v4.1.4) and not on top of last state of svn/trunk branch. In general, it is better to keep the source code history as linear as possible, ie avoid merges. This can be achieve with git rebase command. But sometimes, it is not easy, so a merge is simpler.

Feel free to contact me if you need some support, I am quite familiar with Git nowadays.

No mater for eol, I can do all the messy job to ease the pull request. Keep me informed when you have published all your recent changes.

**Comment by sgano** [comment]
Thanks for the help!  Ouch - yeah I didn't mean to write over an update - but after you mentioned that I think I realize my error now.   I have made all the changes I will be making for a while (plus I will be traveling next week) -- so feel free to tackle what you can.  I appreciate the improvements!
- Shawn

**Comment by guyou** [comment]
Here is a new version of the branch, merging your recent work.

**Pull request merged**
